Warn if the timezone isn't PST (an assumption made by the mozilla test suite)

diff --git a/shell/test/mozilla/run-mozilla-tests.in b/shell/test/mozilla/run-mozilla-tests.in
--- a/shell/test/mozilla/run-mozilla-tests.in
+++ b/shell/test/mozilla/run-mozilla-tests.in
@@ -25,6 +25,10 @@ else
 	exit 1
 fi
 
+if ! date | grep -w PST >/dev/null; then
+	echo "** WARNING: Timezone is not US/Pacific - date tests may fail" >&2
+fi
+
 (
 cd "$MOZDIR"
 
